<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id int
     * @return Product|null
     */
    public function getShopProductAndOfferByProductId($id)
    {
        $query = $this->createQueryBuilder('p')
            ->leftJoin('p.saleOffers',
                'so',
                'WITH',
                'so.userId IS NULL')
            ->where('p.id = :id')
            ->orderBy('p.createdOn', 'DESC')
            ->setParameters([
                'id' => $id
            ])
            ->getQuery();
        /**
         * @var $product Product
         */
        return $query->getOneOrNullResult();
    }

    /**
     * @return array
     */
    public function getShopProductsAndOffers(){
        $query = $this
            ->createQueryBuilder('p')
            ->leftJoin('p.saleOffers',
                'so',
                'WITH',
                'so.userId IS NULL')
            ->orderBy('p.createdOn', 'DESC')
            ->getQuery();
        /**
         * @var $products Product[]
         */
        return $query->getResult();
    }


}
