<?php

namespace AppBundle\Repository;

/**
 * SaleOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleOfferRepository extends \Doctrine\ORM\EntityRepository
{
}
