<?php

namespace AppBundle\Repository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($username)
    {
        return $this->findOneBy([
            'email' => $username
        ]);
    }

    /**
     * @param $registerDate \DateTime
     * @param $cash integer
     */
    public function getUsersByRegisterDateAndCash($registerDate, $cash)
    {
        $qb = $this->createQueryBuilder('u');
        if(!empty($registerDate)){
            $qb->andWhere($qb->expr()->lte('u.registerDate', ':registerDate' ));
                $params['registerDate'] = $registerDate;
        }
        if(!empty($cash)){
            $qb->andWhere('u.cash >= :cash');
                $params['cash'] = $cash;
        }
        $qb->setParameters($params);
        $query = $qb->getQuery();

        return $query->getResult();
    }

}
