<?php

namespace AppBundle\Repository;

/**
 * User2ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User2ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $userId
     * @return array
     */
    public function getUserProductsByUserId($userId)
    {
        $query = $this->createQueryBuilder('up')
            ->join('up.product', 'p')
            ->where('up.userId = :id')
            ->orderBy('up.createdOn', 'DESC')
            ->setParameters([
                'id' => $userId
            ])
            ->getQuery();
        return $query->getResult();
    }
}
