<?php

namespace YudjiePetShopBundle\Repository;

/**
 * User2ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User2ProductRepository extends \Doctrine\ORM\EntityRepository
{
}
